### ISSUE TITLE
Dynamic render with @useContent

### ISSUE THREAD

**Issue by leomascarenhas** [krakenjs/dust-makara-helpers#12]
I'm trying to use @useContent after manually load a dust template (dust.loadSource)
This works fine when I use inside a view that I'll use as a response (res.render), the problem is that I need to get a string to send by email.

I'm able to dust.render and dust.renderSource without problems, but I can't use @useContent. If my code is inside of it, the return is an empty string.

If someone can give me a tip with a little example, I'll appreciate
Thanks

**Comment by leomascarenhas** [comment]
template:

```
{@useContent bundle="default.properties"}
<h3>{welcome.title}</h3>
<p>{user.name},<br/>
<p>{welcome.phrase1}</p><br/>
<p>{welcome.phrase2}<br/>
<a href="{host}:{port}/user/createAuth/{cipher}">Click here!</a></p><br/>
<p>{admin.name}<br/>
<a href="mailto:{admin.email}"> {admin.email}</a></p>
{/useContent}

```

bundles

```
welcome.title=Welcome to {app}
welcome.phrase1=We are glad to have you here!
welcome.phrase2=Please, access the link below and create your authentication.
```

code:

```
var compiledTemplate = dust.compile(src, 'welcome');
dust.loadSource(compiledTemplate);
dust.render('welcome', dust.context({
    intl: { locales: 'en-US' },
    user: user,
    admin: admin,
    host: 'http://localhost',
    port: '8000',
    cipher: cipher
}), function(err, out) {
    console.log('>>>>>> err: ' + err);
    console.log('>>>>>> out: ' + out);
});
```

**Comment by grawk** [comment]
From the example code it isn't clear that you've registered the `dust-makara-helpers` on this instance of `dust`. In the examples, we register `dust-makara-helpers` on the instance which services the express render, but you'd need to make sure you've got them registered here as well. Can you comment on that?

**Comment by leomascarenhas** [comment]
Thanks! I forgot to post here:

var dust = require('dustjs-linkedin');
require('dust-makara-helpers').registerWith(dust, {
    enableMetadata: true,
    autoloadTemplateContent: false
});

I tried this right before the first line of code (dust.compile method)

**Comment by grawk** [comment]
Thanks. Is this running in the same process as a kraken application which registers the makara view engine to express? Or is it a completely separate process?

**Comment by leomascarenhas** [comment]
That's what I thought actually, my template and bundle are in the right place, even so... I still need to loadSource manually.
I'm loading dust with require(), this .js is a layer that I use as a service, inside my controller, where I execute dust.render for views without problems. I don't know If I'm clear enough. Let me know if you understood or how provide better informations.
Thanks

**Comment by grawk** [comment]
It sounds like the answer is your app is attempting to load/compile/render the dust template in the context of handling an express route. Is your express app a kraken app?

**Comment by leomascarenhas** [comment]
it's a kraken app

**Comment by grawk** [comment]
It seems to me that you would need to additionally provide a "loader" property into your dust-makara-helpers registration. E.g.

``` js
var dustMakaraHelpers = require('dust-makara-helpers').registerWith(dust, {
        enableMetadata: true,
        autoloadTemplateContent: false,
        loader: function (context, bundle, cb) {
            var bundler = require('bundler');
            var locale = res.locals.locale;
            bundler.getBundle(locale, bundle), function (err, content) {
                cb(null, content);
            });
        }
    });
```

This is because the main server file for dust-makara-helpers will either use a passed-in loader, or attempt to use the "lookup" method attached to the context by the express view engine:
https://github.com/krakenjs/dust-makara-helpers/blob/0eb27f894c9416d68c1fc79e5cd890fc016e2dad/index.js#L12-L55

The above example hand waves around the "bundler" but this could be based off of [bundalo](https://www.npmjs.com/package/bundalo).

**Comment by leomascarenhas** [comment]
I've created an app to demonstrate my problem:
https://github.com/leonardomascarenhas/testRenderDust

The objective is render a template using the correct language and content.
Steps that I'm trying:
- Take the language from an object
- Take the template and correct bundle
  ...There is a better approach to implement this? 
  Cause the template and bundle will be placed with the others, respecting the project structure
  such as: Dust, take this template name and locale... now render. As we do when using res.render() in the controller.

Thanks for your help ;)

**Comment by leomascarenhas** [comment]
Hello again :)
Someone have an idea to solve this?

**Comment by grawk** [comment]
Hi @leonardomascarenhas. Sorry I haven't had any time to take my example further or look at yours. I will try and look today.

**Comment by grawk** [comment]
Sorry I can't take much time today, due to other priorities. But, I would recommend you use `dust-makara-helpers` instead of registering the two `useContent` and `message` helpers separately. As I've done in my example above. As I mentioned earlier, I "hand waved" around the bundler, and I will go back to that and flesh it out when I have a chance.

**Comment by leomascarenhas** [comment]
hi @grawk, thanks... no problem
I already tried that, I can compile and run the template but cannot use a specific bundle.
I'm not respecting the default structure, I'm using a single properties file for all bundles instead of "locales\language\templateforlder\view"
I'll be glad if you our someone take a look and show me a way to solve this ;)

**Comment by grawk** [comment]
That should be fine, if you use the `useContent` helper and point to your single properties file... I'd really like to help with this when I get free.

**Comment by leomascarenhas** [comment]
The content that should be replaced by translation content are always replaced by an empty string, well, thanks again and let me know if you find something wrong in my project.

**Comment by grawk** [comment]
Hi. Haven't had time to clean this up or put it in a repo, but this is my working controller:

``` js
'use strict';

var IndexModel = require('../models/index');

var lp = {
    "fr-FR": {
        "welcome.properties": {
            "welcome_title": "FR: Welcome to {app}",
            "welcome_phrase1": "FR: We are glad to have you here!",
            "welcome_phrase2": "FR: Please, access the link below and create your authentication."
        }
    },
    "en-US": {
        "welcome.properties": {
            "welcome_title": "US: Welcome to {app}",
            "welcome_phrase1": "US: We are glad to have you here!",
            "welcome_phrase2": "US: Please, access the link below and create your authentication."
        }
    }
};

var fs = require('fs');
var path = require('path');

module.exports = function (router) {

    var model = new IndexModel();
    var freshy = require('freshy');

    var dust = freshy.freshy('dustjs-linkedin');
    require('dust-makara-helpers').registerWith(dust, {
        enableMetadata: false,
        autoloadTemplateContent: false,
        loader: function (context, bundle, cb) {
            cb(null, lp[context.get('locale')][bundle]);
        }
    });
    router.get('/', function (req, res) {
        //do some dust rendering here...
        var src = fs.readFileSync(path.resolve(__dirname, '../public/templates/welcome.dust')).toString();
        dust.loadSource(dust.compile(src, 'welcome'));
        dust.render('welcome', {
            app: 'welcomeApp',
            templateName: 'welcome',
            locale: 'fr-FR',
            user: 'foo',
            admin: 'James',
            email: 'james@localhost',
            host: 'http://localhost',
            port: '8000',
            cipher: 'abc123'
        }, function(err, out) {
            console.log('>>>>>> err: ' + err);
            console.log('>>>>>> out: ' + out);
            res.render('index', model);

        });
    });

};

```

I've inlined the content bundle JSON object, but you'd want to use the bundalo module in its place (can work that out later if you like). Also note I've replaced your periods in your content keys with underscores because the `@message` helper will not find those accurately due to this:
https://github.com/krakenjs/dust-message-helper/blob/master/index.js#L18

Also, modified the template to use the `@message` helper:

``` html
{@useContent bundle="welcome.properties"}
<h3>{@message type="content" key="welcome_title"/}</h3>
<p>{user},<br/>
<p>{@message type="content" key="welcome_phrase1"/}</p><br/>
<p>{@message type="content" key="welcome_phrase2"/}<br/>
    <a href="{host}:{port}/user/createAuth/{cipher}">Click here!</a></p><br/>
<p>{admin}<br/>
    <a href="mailto:{email}"> {email}</a></p>
{/useContent}
```

This works for me, although I'm not advocating it is the cleanest pattern. Anyway, can move it along more as I find time but wanted to leave you with something in the meantime.

**Comment by grawk** [comment]
Hi @leonardomascarenhas. I'm going to close this issue. If/when you get back to actively looking at this, feel free to re-open.

**Comment by leomascarenhas** [comment]
Hello @grawk 
Thank you very much for your solution and sorry for the delay... it worked here.
Unfortunately I'm using a .properties file and I don't think that the way I've implemented here was the best approach.
What do you think?

```
{@useContent bundle=""}
<h3>{@message type="content" key="welcome_title"/} to {app}</h3>
<p>{@message type="content" key="welcome_hello"/} {userName}<br/>
{/useContent}
```

I'm using the https://www.npmjs.com/package/properties to parse the .properties file...

```
var fs = require('fs');
var makara = require('makara');
var path = require('path');
var freshy = require('freshy');
var dust = freshy.freshy('dustjs-linkedin');
var properties = require ("properties");

var UserService = function () {};

require('dust-makara-helpers').registerWith(dust, {
    enableMetadata: false,
    autoloadTemplateContent: false,
    loader: function (context, bundle, cb) {
        cb(null, context.get('userBundle'));
    }
});

UserService.prototype.testRender = function (user, callback) {
    var localeArr = user.locale.split("-");
    var lang = localeArr[0];
    var country = localeArr[1];
    var file = path.resolve(__dirname, '../locales/'+country+'/'+lang+'/default.properties');

    properties.parse(file, { path: true }, function (err, jsonBundle) {
        if (err)
          callback(err);

        var src = fs.readFileSync(path.resolve(__dirname, '../public/templates/users/welcome.dust')).toString();
        dust.loadSource(dust.compile(src, 'welcome'));
        dust.render('welcome', {
            app: 'WelcomeApp',
            templateName: 'welcome',
            locale: user.locale,
            userName: user.name,
            userBundle: jsonBundle
        }, function(err, out) {
            callback(null, out);
        });
    });
};
```
