### ISSUE TITLE
consider removing requirement of .properties for each .dust

### ISSUE THREAD

**Issue by grawk** [krakenjs/dust-makara-helpers#5]
Currently it would be required to have a .properties file for each .dust file. Some files may get their content entirely from their data model, or else have no localizable content.

**Comment by grawk** [comment]
can this be switched by setting `autoLoadTemplateContent: false`?

**Comment by aredridel** [comment]
Yeah. I'm torn on this: A common error is not having a content bundle, and displaying placeholders or nothing. This error makes that explicit.

One can turn off a lot of the complexity in this module by turning off autoloadTemplateContent, and with it, the path that triggers this error.

**Comment by aredridel** [comment]
TL;DR: Yes, turn off `autoloadTemplateContent`, and use `@useContent` tags to load it explicitly.

**Comment by grawk** [comment]
Is that documented or only in the source code?

**Comment by aredridel** [comment]
The option is documented; that it avoids this error is not.

**Comment by grawk** [comment]
I see it now. Sorry I was looking at README on the default `v3.x` branch, where it is not documented.

**Comment by aredridel** [comment]
Whoops. time to fix that default.
