### ISSUE TITLE
Allow bundle.properties omissions for templates not requiring internationalization

### ISSUE THREAD

**Issue by mvandervliet** [krakenjs/dust-makara-helpers#7]
In cases where applications use many partials, it is not unusual for certain templates to not use any internationalization whatsoever. As such, it's proposed to add an option as follows:

``` javascript
{
  requireTemplateContent: false
}
```

Setting to false would avoid render errors when associative `.properties` bundles are not present.

Pull request #6 opened

**Comment by aredridel** [comment]
Ah, let's talk on #6 then!
